### ISSUE TITLE
upsampling from 8k to 16k

### ISSUE THREAD

**Issue by MrityunjoyS** [Picovoice/web-voice-processor#1]
Can you please suggest something on up sapmpling similar to this down sampling that you did

**Comment by kenarsa** [comment]
you can repeat each sample twice. keep in mind the freq content is already gone though...

**Comment by MrityunjoyS** [comment]
Thanks for your response. Actually, I'll be recording my audio at 8k sample rate only, and then need to up-sample it to 16k, that's why I was thinking if its possible to change the calculation part a bit accordingly.
