### ISSUE TITLE
Uncaught TypeError: engine.postMessage is not a function     at web_voice_processor.js:27

### ISSUE THREAD

**Issue by Sudarshan-gurav** [Picovoice/web-voice-processor#2]
I am facing this engine issue as please help into it 

`Uncaught TypeError: engine.postMessage is not a function
    at web_voice_processor.js:27
    at Array.forEach (<anonymous>)
    at Worker.downsampler.onmessage (web_voice_processor.js:26)`

also getting below warning :

`wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
(anonymous) @ VM4 pv_porcupine.js:8
Promise.then (async)
(anonymous) @ VM4 pv_porcupine.js:8
Promise.then (async)
instantiateAsync @ VM4 pv_porcupine.js:8
createWasm @ VM4 pv_porcupine.js:8
(anonymous) @ VM4 pv_porcupine.js:8
(anonymous) @ VM5 porcupine.js:27
(anonymous) @ VM5 porcupine.js:181
(anonymous) @ VM3 porcupine_worker.js:7
`
2.
`falling back to ArrayBuffer instantiation` 

If you have any proper step which do we need to use or steps please sugeest

I have copy same index.html as you provide for 'Hey Edison'

**Comment by dbartle** [comment]
Can you please include more source code so that we can understand the issue? Or are you trying to run the Porcupine demo as-is?

The warning should not prevent it from working. That occurs when the web server does not set the MIME type on the .wasm file, which is common, since WebAssembly is not typically configured out-of-the box.

**Comment by dbartle** [comment]
Anyway, I don't see any actual bug/issue with the demo. And if you're simply trying to get "Hey Edison" to work, [follow the instructions in the readme](https://github.com/Picovoice/porcupine/tree/master/demo/javascript) and get that working first. If you encounter a bug with that, please open an issue on that repo. But the demo is working fine for me, so I'm closing this issue.

**Comment by Sudarshan-gurav** [comment]
Yes , No bug , Actually I am beginner in JavaScript 
After follow the step Hey Edison is working
