### ISSUE TITLE
createScriptProcessor

### ISSUE THREAD

**Issue by tomburge** [Picovoice/web-voice-processor#4]
Is the voice processor going to be updated to use a newer method?

This method is already deprecated according to: https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/createScriptProcessor

**Comment by dbartle** [comment]
It is indeed deprecated. Awkwardly though, its replacement (AudioWorklet) is not supported in Safari or Safari mobile. It may make sense at some point to add a code switch based on AudioWorklet support but that obsolete method can't go away until Apple updates Safari to modern standards.

**Comment by dbartle** [comment]
I closed the issue since action can't be taken on it, but I'm going to reopen since this should be visible. Looks like support is "right around the corner": [https://bugs.webkit.org/show_bug.cgi?id=182506](https://bugs.webkit.org/show_bug.cgi?id=182506)

**Comment by tomburge** [comment]
So once this method is supported, what kind of priority will this item be?

**Comment by dbartle** [comment]
Difficult to say; I want to keep the issue open and see if there's more demand for this.

Even without Safari I know it would be useful for e.g. Electron. We'll probably need to keep the old method alongside and do feature detection, since old Safari won't disappear overnight either (unfortunately!).

**Comment by tomburge** [comment]
Thanks! Good to know!

**Comment by ksyeo1010** [comment]
This has been resolved in https://github.com/Picovoice/web-voice-processor/pull/28.
