### ISSUE TITLE
Sending audio to LLMs: support for other mimetypes?

### ISSUE THREAD

**Issue by tval2** [Picovoice/web-voice-processor#65]
Maybe a dumb question, I am trying to use this SDK since it's easily compatible with other pico models but then when I want to prompt gpt4-o, claude, or gemini with audio I get an issue in that they usually want wav, ogg, mp3 etc. 

From the docs:
```
Audio data is supported in the following common audio format [MIME types](https://developers.google.com/drive/api/guides/ref-export-formats):
WAV - audio/wav
MP3 - audio/mp3
AIFF - audio/aiff
AAC - audio/aac
OGG Vorbis - audio/ogg
FLAC - audio/flac
```

is there a parameter to pass to pico to change this or do I just need to write some custom functions? I'm trying to keep latency down as much as possible

**Comment by kenarsa** [comment]
No, and you probably don't need it to be real-time, so you should use whatever standard browser API is available to you.
